---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: open5gran-anyuid
subjects:
  - kind: ServiceAccount
    name: default
    namespace: open5gran
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:anyuid'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: open5gran-hostaccess
subjects:
  - kind: ServiceAccount
    name: default
    namespace: open5gran
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:hostaccess'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: open5gran-hostmount-anyuid
subjects:
  - kind: ServiceAccount
    name: default
    namespace: open5gran
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:hostmount-anyuid'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: open5gran-privileged
subjects:
  - kind: ServiceAccount
    name: default
    namespace: open5gran
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:privileged'
