apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-multus
spec:
  config: '{"cniVersion": "0.3.1", "type": "macvlan", "mode": "bridge", "master": "ens4f0", "ipam": { "type": "static"} }'
